### ISSUE TITLE
Undefined method add_system_framework with latest ib 0.3.2 gem and RM 2.9 / iOS 7

### ISSUE THREAD

**Issue by matthewsinclair** [rubymotion/ib#36]
I've just started to get this error with gem 'ib' 0.3.2 under RM 2.9 / iOS7 / xcodeproj-0.11.0

```
$ rake ib:project
rake aborted!
undefined method `add_system_framework' for #<Xcodeproj::Project:0x007ffbf2a463e8>
...
```

Any ideas?
